version: "3.5"

services:
    bp_php:
        container_name: php
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor/
        build: .
        command: php artisan serve --host=0.0.0.0
        restart: always
        depends_on:
            - bp_db
    bp_db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: mysqld --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        volumes:
            - ./database/mysql-data:/var/lib/mysql:rw
volumes:
    mysql-data:
